### ISSUE TITLE
1min_clips folder

### ISSUE THREAD

**Issue by neeek2303** [deepimagination/TalkingHead-1KH#2]
Hi, after running bash ```videos_download_and_crop.sh``` small I got this message and folder ```small/cropped_clips``` appears to be empty :

Using pool size of 8
File exists: --Y9imYnfBw
File exists: -7TMJtnhiPM
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 7632.95it/s]
Elapsed time: 0.02
videos_download_and_crop.sh: line 7: ./videos_split.sh: Permission denied
Using pool size of 8
Input file small/1min_clips/--Y9imYnfBw_0000.mp4 does not exist, skipping
Input file small/1min_clips/--Y9imYnfBw_0000.mp4 does not exist, skipping
Input file small/1min_clips/-7TMJtnhiPM_0000.mp4 does not exist, skipping
Input file small/1min_clips/-7TMJtnhiPM_0000.mp4 does not exist, skipping
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 12228.29it/s]
Elapsed time: 0.02

UPDATE:
It worked if I  change  ```./videos_split.sh ${dataset}/raw_videos ${dataset}/1min_clips```  in ```videos_download_and_crop.sh``` to ```bash videos_split.sh ${dataset}/raw_videos ${dataset}/1min_clips```

**Comment by tcwang0509** [comment]
Thanks. Closing it as it's resolved.
