### ISSUE TITLE
Is the download code still working?

### ISSUE THREAD

**Issue by KelestZ** [deepimagination/TalkingHead-1KH#3]
Hi, thanks for releasing the dataset. I am facing a download issue:

  File "/anaconda3/lib/python3.8/site-packages/pytube/cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'

But a few days ago I successfully downloaded some. So I was wondering this is the issue for me only or for all?
Btw, I have pytube.__version__='11.0.2'.

**Comment by tcwang0509** [comment]
This seems to be an issue from pytube: https://github.com/pytube/pytube/issues/1218
Need to wait for them to resolve it...

**Comment by KelestZ** [comment]
Close the issue.
This solution works for me.
https://github.com/pytube/pytube/issues/1218#issuecomment-1026499476

**Comment by KelestZ** [comment]
Update: 
The solution above didn't solve the issue for all videos. To me, over 50% of videos are downloaded **unsuccessfully**.
