### ISSUE TITLE
Black videos during trimming

### ISSUE THREAD

**Issue by FebOne1** [deepimagination/TalkingHead-1KH#4]
Hi, the dataset is interesting. 
I get 3/4 black videos when generating the small dataset. I also notice that the trim function works from time to time when I modify the start/end_frames, though the beginning frames might be still black. Could anyone tell the reason and how to fix it? 

I'm using ffmpeg 2.8.15 built with gcc 4.8.5, and ffmpeg-python 0.2.0.

Update:
I also tested this command in terminal, but still get a black output video. So seems it's due to the version of ffmpeg?
>> ffmpeg -i -7TMJtnhiPM_0000.mp4 -vf trim=start_frame=50:end_frame=80 -an output80.mp4

**Comment by FebOne1** [comment]
> 



> I am also facing the same issue.

I figured out my issue which is because I was using default QuickTime player to open the videos. Switching to another media player, i.e., VLC or IINA, works. Another sanity check is to use OpenCV to read the video.

**Comment by Griffin98** [comment]
Thanks. I also realized the same. When i extracted frames from the videos. It was all good. I switched my player and it was all good.

Cheers
