### ISSUE TITLE
no audio?

### ISSUE THREAD

**Issue by Dorniwang** [deepimagination/TalkingHead-1KH#8]
The downloaded video has no sound?

**Comment by sunyasheng** [comment]
Have you figured it out? I also find that they do not contain audio.     
I've tried to download audio by
```
audio_stream = yt.streams.filter(subtype='mp4', only_audio=True).first()
```
But it comes from a different video.

**Comment by Dorniwang** [comment]
> Have you figured it out? I also find that they do not contain audio. I've tried to download audio by
> 
> ```
> audio_stream = yt.streams.filter(subtype='mp4', only_audio=True).first()
> ```
> 
> But it comes from a different video.

yeah, i use the following one to download video with audio:
`stream = yt.streams.get_highest_resolution()`
but the resolution of video is 720p rather than 1080p, and the val data is 1080p. Fortunately, the training data is 720p, so i think it's not a big problem.
